services:
  # Chat UI
  chat-view:
    image: oven/bun:latest
    working_dir: /app
    container_name: chat-view
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DOMAIN=${DOMAIN:-localhost}
    command: bash -c "bun i; bun dev"
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: ${DOMAIN:-localhost}
      caddy.reverse_proxy: "{{upstreams 3000}}"

  # #  Caddy - proxy server router for containers 
  # # sudo docker network create caddy
  domain-router:  
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: domain-router
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/caddy/data:/data
    restart: unless-stopped
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy

networks:
  caddy:
    external: true 