name = "starter-next-better-drizzle"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "starter-db"
database_id = "your-database-id-here"

[env.production]
name = "starter-next-better-drizzle-prod"

[env.staging]
name = "starter-next-better-drizzle-staging"

# Environment variables
[vars]
NODE_ENV = "production"

# Secrets (set these with wrangler secret put)
# BETTER_AUTH_SECRET
# GOOGLE_CLIENT_ID
# GOOGLE_CLIENT_SECRET
# GITHUB_CLIENT_ID
# GITHUB_CLIENT_SECRET
# RESEND_API_KEY
# STRIPE_SECRET_KEY
# STRIPE_WEBHOOK_SECRET
# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY 