name = "starterdocs"
compatibility_date = "2024-02-08"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"
site.bucket = "./.cloudflare/public"


[[d1_databases]]
binding = "DB" 
database_name = "serverless-docs-db"
database_id = "ad291768-5128-428d-995f-8084ea208594"


[observability.logs]
enabled = true