

# name: Deploy to Cloudflare Workers

# on:
#   push:
#     branches:
#       - main

# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v4

#       - name: Publish with Wrangler
#         uses: cloudflare/wrangler-action@v3
#         with:
#           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#           # Uncomment the next line if your wrangler.toml is in a subdirectory
#           workingDirectory: ./apps/starter-docs-svelte
#           # Provide extra Wrangler CLI commands if needed:
#           command: deploy

# # CLOUDFLARE_API_TOKEN: Generate in Cloudflare dashboard with "Edit Cloudflare Workers" permissions.

# # CLOUDFLARE_ACCOUNT_ID: Find in your Cloudflare account settings.

# # Add both as GitHub repository secrets under Settings > Secrets > Actions.
